### ISSUE TITLE
有概率无法开门的问题

### ISSUE THREAD

**Issue by SiriusNEO** [cmd2001/jLock#1]
![K60(0MD7$ZL3XF0RX7{NKTP](https://user-images.githubusercontent.com/41781658/189592616-a90a4862-00b5-4b01-a5db-fea72d34dfa5.png)

```
INFO:root:Current time is 1662966061361014892 (unixNano)
INFO:root:Last Session Was Created At 1662962843372606403 (unixNano)
INFO:root:Loading Last Session
INFO:root:Collecting Cookies
INFO:root:Cookies Coollected Successfully!
INFO:root:Opening Door with ID 5f75c3a21a74423f9ab0ab685a6a6aa3
INFO:root:Door should be Opened
```

终端已经出现成功信息，但是门却没有开

**Comment by cmd2001** [comment]
Check your ROOM_ID in `config.py`.

You can get the 40-bit roomid by scanning the QR code on your door. However, the last 8 bits should be removed.

**Comment by cmd2001** [comment]
If that does not work, try to shorten `REFRESH_SESSION_PERIOD` in config.py or remove `last_session_time.txt`.

This will be fixed in next commit.

**Comment by cmd2001** [comment]
Already fixed.
